/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  SurveyBlocksApi,
  SurveyFlowsApi,
  SurveyLanguagesApi,
  SurveyOptionsApi,
  SurveyQuestionsApi,
  SurveyQuotasApi,
  SurveyTranslationsApi,
  SurveyVersionsApi,
  SurveysApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { QualtricsCustom } from "./client-custom";

export class Qualtrics extends QualtricsCustom {
  readonly surveyBlocks: SurveyBlocksApi;
  readonly surveyFlows: SurveyFlowsApi;
  readonly surveyLanguages: SurveyLanguagesApi;
  readonly surveyOptions: SurveyOptionsApi;
  readonly surveyQuestions: SurveyQuestionsApi;
  readonly surveyQuotas: SurveyQuotasApi;
  readonly surveyTranslations: SurveyTranslationsApi;
  readonly surveyVersions: SurveyVersionsApi;
  readonly surveys: SurveysApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.surveyBlocks = new SurveyBlocksApi(configuration);
    this.surveyFlows = new SurveyFlowsApi(configuration);
    this.surveyLanguages = new SurveyLanguagesApi(configuration);
    this.surveyOptions = new SurveyOptionsApi(configuration);
    this.surveyQuestions = new SurveyQuestionsApi(configuration);
    this.surveyQuotas = new SurveyQuotasApi(configuration);
    this.surveyTranslations = new SurveyTranslationsApi(configuration);
    this.surveyVersions = new SurveyVersionsApi(configuration);
    this.surveys = new SurveysApi(configuration);
  }

}
