/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 *  Lightweight Directory Access Protocol
 * @export
 * @interface AuthenticatorFlowElementSSOOptionsLdap
 */
export interface AuthenticatorFlowElementSSOOptionsLdap {
    [key: string]: any;

    /**
     * Hostname.
     * @type {string}
     * @memberof AuthenticatorFlowElementSSOOptionsLdap
     */
    'Hostname'?: string;
    /**
     * Port.
     * @type {string}
     * @memberof AuthenticatorFlowElementSSOOptionsLdap
     */
    'Port'?: string;
    /**
     * Email field.
     * @type {string}
     * @memberof AuthenticatorFlowElementSSOOptionsLdap
     */
    'EmailField'?: string;
    /**
     * External data reference field.
     * @type {string}
     * @memberof AuthenticatorFlowElementSSOOptionsLdap
     */
    'ExternalDataReferenceField'?: string;
    /**
     * Filter.
     * @type {string}
     * @memberof AuthenticatorFlowElementSSOOptionsLdap
     */
    'Filter'?: string;
    /**
     * Field for first name.
     * @type {string}
     * @memberof AuthenticatorFlowElementSSOOptionsLdap
     */
    'FirstNameField'?: string;
    /**
     * Field for last name.
     * @type {string}
     * @memberof AuthenticatorFlowElementSSOOptionsLdap
     */
    'LastNameField'?: string;
}

