/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AuthenticatorFlowElementOptions } from './authenticator-flow-element-options';
import { AuthenticatorFlowElementPanelData } from './authenticator-flow-element-panel-data';
import { AuthenticatorFlowElementSSOOptions } from './authenticator-flow-element-ssooptions';
import { BranchLogic } from './branch-logic';
import { FlowInner } from './flow-inner';

/**
 * Require respondents to authenticate (login)
 * @export
 * @interface AuthenticatorFlowElement
 */
export interface AuthenticatorFlowElement {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof AuthenticatorFlowElement
     */
    'Type': AuthenticatorFlowElementTypeEnum;
    /**
     * Unique identifier. Should be of form `FL_1`
     * @type {string}
     * @memberof AuthenticatorFlowElement
     */
    'FlowID'?: string;
    /**
     * 
     * @type {AuthenticatorFlowElementPanelData}
     * @memberof AuthenticatorFlowElement
     */
    'PanelData': AuthenticatorFlowElementPanelData;
    /**
     * 
     * @type {BranchLogic}
     * @memberof AuthenticatorFlowElement
     */
    'FieldData': BranchLogic;
    /**
     * If true, filter data fields.
     * @type {boolean}
     * @memberof AuthenticatorFlowElement
     */
    'FilterDataFields': boolean;
    /**
     * 
     * @type {AuthenticatorFlowElementSSOOptions}
     * @memberof AuthenticatorFlowElement
     */
    'SSOOptions': AuthenticatorFlowElementSSOOptions;
    /**
     * 
     * @type {AuthenticatorFlowElementOptions}
     * @memberof AuthenticatorFlowElement
     */
    'Options': AuthenticatorFlowElementOptions;
    /**
     * Definition of the inner flow elements (maximum of 5000)
     * @type {Array<FlowInner>}
     * @memberof AuthenticatorFlowElement
     */
    'Flow'?: Array<FlowInner>;
}

type AuthenticatorFlowElementTypeEnum = 'Authenticator'


