/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AuthenticatorFlowElementSSOOptionsLdap } from './authenticator-flow-element-ssooptions-ldap';
import { AuthenticatorFlowElementSSOOptionsRespondentMapInner } from './authenticator-flow-element-ssooptions-respondent-map-inner';
import { AuthenticatorFlowElementSSOOptionsToken } from './authenticator-flow-element-ssooptions-token';

/**
 * SSO options.
 * @export
 * @interface AuthenticatorFlowElementSSOOptions
 */
export interface AuthenticatorFlowElementSSOOptions {
    [key: string]: any;

    /**
     * Capture respondent info.
     * @type {string}
     * @memberof AuthenticatorFlowElementSSOOptions
     */
    'CaptureRespondentInfo'?: AuthenticatorFlowElementSSOOptionsCaptureRespondentInfoEnum;
    /**
     * Central Authentication Service.
     * @type {Array<string>}
     * @memberof AuthenticatorFlowElementSSOOptions
     */
    'cas'?: Array<string>;
    /**
     * 
     * @type {AuthenticatorFlowElementSSOOptionsLdap}
     * @memberof AuthenticatorFlowElementSSOOptions
     */
    'ldap'?: AuthenticatorFlowElementSSOOptionsLdap;
    /**
     * Respondent map.
     * @type {Array<AuthenticatorFlowElementSSOOptionsRespondentMapInner>}
     * @memberof AuthenticatorFlowElementSSOOptions
     */
    'respondentMap'?: Array<AuthenticatorFlowElementSSOOptionsRespondentMapInner>;
    /**
     * 
     * @type {AuthenticatorFlowElementSSOOptionsToken}
     * @memberof AuthenticatorFlowElementSSOOptions
     */
    'token'?: AuthenticatorFlowElementSSOOptionsToken;
    /**
     * SSO option type.
     * @type {string}
     * @memberof AuthenticatorFlowElementSSOOptions
     */
    'Type': AuthenticatorFlowElementSSOOptionsTypeEnum;
    /**
     * Use Panel.
     * @type {string}
     * @memberof AuthenticatorFlowElementSSOOptions
     */
    'UsePanel'?: AuthenticatorFlowElementSSOOptionsUsePanelEnum;
    /**
     * Use person.
     * @type {string}
     * @memberof AuthenticatorFlowElementSSOOptions
     */
    'UsePerson'?: AuthenticatorFlowElementSSOOptionsUsePersonEnum;
    /**
     * Use SSO.
     * @type {string}
     * @memberof AuthenticatorFlowElementSSOOptions
     */
    'UseSSO'?: AuthenticatorFlowElementSSOOptionsUseSSOEnum;
}

type AuthenticatorFlowElementSSOOptionsCaptureRespondentInfoEnum = 'true' | 'false'
type AuthenticatorFlowElementSSOOptionsTypeEnum = 'Token' | 'CAS' | 'LDAP' | 'LTI' | 'Shibboleth' | 'UseBrandSettings' | 'GoogleOpenID' | 'Facebook'
type AuthenticatorFlowElementSSOOptionsUsePanelEnum = 'true' | 'false'
type AuthenticatorFlowElementSSOOptionsUsePersonEnum = 'true' | 'false'
type AuthenticatorFlowElementSSOOptionsUseSSOEnum = 'true' | 'false'


