/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BlockOptionsLoopingOptions } from './block-options-looping-options';
import { BlockOptionsRandomization } from './block-options-randomization';
import { LibraryID } from './library-id';

/**
 * 
 * @export
 * @interface BlockOptions
 */
export interface BlockOptions {
    [key: string]: any;

    /**
     * Prevents modification of the block and its contents
     * @type {string}
     * @memberof BlockOptions
     */
    'BlockLocking'?: BlockOptionsBlockLockingEnum;
    /**
     * Authorization to modify the block
     * @type {string}
     * @memberof BlockOptions
     */
    'BlockPassword'?: string;
    /**
     * 
     * @type {string}
     * @memberof BlockOptions
     */
    'BlockVisiblity'?: BlockOptionsBlockVisiblityEnum;
    /**
     * 
     * @type {string}
     * @memberof BlockOptions
     */
    'RandomizeQuestions'?: BlockOptionsRandomizeQuestionsEnum;
    /**
     * Loop & Merge type
     * @type {string}
     * @memberof BlockOptions
     */
    'Looping'?: BlockOptionsLoopingEnum;
    /**
     * 
     * @type {BlockOptionsLoopingOptions}
     * @memberof BlockOptions
     */
    'LoopingOptions'?: BlockOptionsLoopingOptions;
    /**
     * 
     * @type {BlockOptionsRandomization}
     * @memberof BlockOptions
     */
    'Randomization'?: BlockOptionsRandomization;
    /**
     * The text on the next button at preview and runtime, or if nextButtonMID is set, the name of the message referred to there
     * @type {string}
     * @memberof BlockOptions
     */
    'NextButton'?: string;
    /**
     * The text on the previous button at preview and runtime, or if previousButtonMID is set, the name of the message referred to there
     * @type {string}
     * @memberof BlockOptions
     */
    'PreviousButton'?: string;
    /**
     * 
     * @type {LibraryID}
     * @memberof BlockOptions
     */
    'nextButtonLibraryID'?: LibraryID;
    /**
     * The unique identifier for the message.
     * @type {string}
     * @memberof BlockOptions
     */
    'nextButtonMID'?: string;
    /**
     * The unique identifier for the message.
     * @type {string}
     * @memberof BlockOptions
     */
    'previousButtonLibraryID'?: string;
}

type BlockOptionsBlockLockingEnum = 'true' | 'false'
type BlockOptionsBlockVisiblityEnum = 'Collapsed' | 'Expanded'
type BlockOptionsRandomizeQuestionsEnum = 'false' | 'RandomWithXPerPage' | 'RandomWithOnlyX' | 'Advanced'
type BlockOptionsLoopingEnum = 'None' | 'Static' | 'Question'


