/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Locator } from './locator';

/**
 * Options and configuration for Loop & Merge. Includes input fields and randomization
 * @export
 * @interface BlockOptionsLoopingOptions
 */
export interface BlockOptionsLoopingOptions {
    [key: string]: any;

    /**
     * 
     * @type {Locator}
     * @memberof BlockOptionsLoopingOptions
     */
    'ChoiceGroupLocator'?: Locator;
    /**
     * 
     * @type {Locator}
     * @memberof BlockOptionsLoopingOptions
     */
    'Locator'?: Locator;
    /**
     * The unique identifier for the question.
     * @type {string}
     * @memberof BlockOptionsLoopingOptions
     */
    'QID'?: string;
    /**
     * Type of randomization to apply to the loop ordering
     * @type {string}
     * @memberof BlockOptionsLoopingOptions
     */
    'Randomization'?: BlockOptionsLoopingOptionsRandomizationEnum;
    /**
     * The (static) fields in the Loop & Merge
     * @type {{ [key: string]: object; }}
     * @memberof BlockOptionsLoopingOptions
     */
    'Static'?: { [key: string]: object; };
}

type BlockOptionsLoopingOptionsRandomizationEnum = 'None' | 'Subset' | 'All'


