/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BlockOptionsRandomizationAdvanced } from './block-options-randomization-advanced';

/**
 * The configuration for the type of Randomization to apply. Many options based on 3 types of Randomization in RandomizeQuestions
 * @export
 * @interface BlockOptionsRandomization
 */
export interface BlockOptionsRandomization {
    [key: string]: any;

    /**
     * 
     * @type {BlockOptionsRandomizationAdvanced}
     * @memberof BlockOptionsRandomization
     */
    'Advanced'?: BlockOptionsRandomizationAdvanced;
    /**
     * Whether or not to balance the number of times each Randomization.Advanced.RandomSubSet question is displayed across all respondents
     * @type {boolean}
     * @memberof BlockOptionsRandomization
     */
    'EvenPresentation'?: boolean;
}

