/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BranchLogic } from './branch-logic';

/**
 * Branch flow element.
 * @export
 * @interface BranchFlowElement
 */
export interface BranchFlowElement {
    [key: string]: any;

    /**
     * Type of branch flow.
     * @type {string}
     * @memberof BranchFlowElement
     */
    'Type'?: BranchFlowElementTypeEnum;
    /**
     * Unique identifier. Should be of form `FL_1`
     * @type {string}
     * @memberof BranchFlowElement
     */
    'FlowID'?: string;
    /**
     * A user-provided description of the block flow element.
     * @type {string}
     * @memberof BranchFlowElement
     */
    'Description'?: string;
    /**
     * 
     * @type {BranchLogic}
     * @memberof BranchFlowElement
     */
    'BranchLogic'?: BranchLogic;
}

type BranchFlowElementTypeEnum = 'Branch'


