/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BranchLogicValue } from './branch-logic-value';

/**
 * Send respondents down different paths in the survey. See Qualtics Documentation for more information on [Branch Logic](https://www.qualtrics.com/support/survey-platform/survey-module/survey-flow/standard-elements/branch-logic/)
 * @export
 * @interface BranchLogic
 */
export interface BranchLogic {
    [key: string]: BranchLogicValue | any;

    /**
     * Type of branch logic.
     * @type {string}
     * @memberof BranchLogic
     */
    'Type': BranchLogicTypeEnum;
}

type BranchLogicTypeEnum = 'BooleanExpression'


