/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Language } from './language';
import { QuestionConfiguration } from './question-configuration';
import { Validation } from './validation';

/**
 * 
 * @export
 * @interface DescriptiveTextQuestionDefinition
 */
export interface DescriptiveTextQuestionDefinition {
    /**
     * 
     * @type {QuestionConfiguration}
     * @memberof DescriptiveTextQuestionDefinition
     */
    'Configuration': QuestionConfiguration;
    /**
     * The tag to identify the question in exported data.
     * @type {string}
     * @memberof DescriptiveTextQuestionDefinition
     */
    'DataExportTag': string;
    /**
     * 
     * @type {boolean}
     * @memberof DescriptiveTextQuestionDefinition
     */
    'DefaultChoices': boolean;
    /**
     * 
     * @type {Language}
     * @memberof DescriptiveTextQuestionDefinition
     */
    'Language': Language;
    /**
     * 
     * @type {number}
     * @memberof DescriptiveTextQuestionDefinition
     */
    'NextAnswerId'?: number;
    /**
     * 
     * @type {number}
     * @memberof DescriptiveTextQuestionDefinition
     */
    'NextChoiceId'?: number;
    /**
     * 
     * @type {string}
     * @memberof DescriptiveTextQuestionDefinition
     */
    'QuestionDescription': string;
    /**
     * The unique identifier for the question.
     * @type {string}
     * @memberof DescriptiveTextQuestionDefinition
     */
    'QuestionID'?: string;
    /**
     * Text for the question.
     * @type {string}
     * @memberof DescriptiveTextQuestionDefinition
     */
    'QuestionText': string;
    /**
     * 
     * @type {string}
     * @memberof DescriptiveTextQuestionDefinition
     */
    'QuestionType': DescriptiveTextQuestionDefinitionQuestionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof DescriptiveTextQuestionDefinition
     */
    'Selector': DescriptiveTextQuestionDefinitionSelectorEnum;
    /**
     * 
     * @type {Validation}
     * @memberof DescriptiveTextQuestionDefinition
     */
    'Validation': Validation;
}

type DescriptiveTextQuestionDefinitionQuestionTypeEnum = 'DB'
type DescriptiveTextQuestionDefinitionSelectorEnum = 'TB'


