/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Logic expression for a Device Type
 * @export
 * @interface DeviceTypeExpression
 */
export interface DeviceTypeExpression {
    [key: string]: any;

    /**
     * Logic type of the device type expression.
     * @type {string}
     * @memberof DeviceTypeExpression
     */
    'LogicType': DeviceTypeExpressionLogicTypeEnum;
    /**
     * Operation.
     * @type {string}
     * @memberof DeviceTypeExpression
     */
    'LeftOperand': DeviceTypeExpressionLeftOperandEnum;
    /**
     * Operator.
     * @type {string}
     * @memberof DeviceTypeExpression
     */
    'Operator'?: DeviceTypeExpressionOperatorEnum;
    /**
     * The type of device type expression.
     * @type {string}
     * @memberof DeviceTypeExpression
     */
    'Type': DeviceTypeExpressionTypeEnum;
    /**
     * A user-provided description field.
     * @type {string}
     * @memberof DeviceTypeExpression
     */
    'Description': string;
}

type DeviceTypeExpressionLogicTypeEnum = 'DeviceType'
type DeviceTypeExpressionLeftOperandEnum = 'mobile' | 'Mobile' | 'blackberry' | 'android' | 'ipad' | 'iphone' | 'ipod' | 'opera' | 'palm' | 'windows' | 'generic'
type DeviceTypeExpressionOperatorEnum = 'Is' | 'IsNot'
type DeviceTypeExpressionTypeEnum = 'Expression'


