/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ComparisonOperators } from './comparison-operators';
import { Locator } from './locator';

/**
 * Logic expression for a Embedded Data type
 * @export
 * @interface EmbeddedDataExpression
 */
export interface EmbeddedDataExpression {
    [key: string]: any;

    /**
     * Logic type of the embedded data expression.
     * @type {string}
     * @memberof EmbeddedDataExpression
     */
    'LogicType': EmbeddedDataExpressionLogicTypeEnum;
    /**
     * A user-provided description field.
     * @type {string}
     * @memberof EmbeddedDataExpression
     */
    'Description'?: string;
    /**
     * Comparison operators.
     * @type {ComparisonOperators}
     * @memberof EmbeddedDataExpression
     */
    'Operator'?: ComparisonOperators;
    /**
     * 
     * @type {Locator}
     * @memberof EmbeddedDataExpression
     */
    'LeftOperand'?: Locator;
    /**
     * Operation.
     * @type {string}
     * @memberof EmbeddedDataExpression
     */
    'RightOperand'?: string;
    /**
     * Type of embedded data expression.
     * @type {string}
     * @memberof EmbeddedDataExpression
     */
    'Type': EmbeddedDataExpressionTypeEnum;
}

type EmbeddedDataExpressionLogicTypeEnum = 'EmbeddedField'
type EmbeddedDataExpressionTypeEnum = 'Expression'


