/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmailThankYou } from './email-thank-you';
import { ResponseSummary } from './response-summary';
import { SurveyTermination } from './survey-termination';
import { YesNoEmptyString } from './yes-no-empty-string';

/**
 * 
 * @export
 * @interface EndSurveyOptions
 */
export interface EndSurveyOptions {
    /**
     * Whether to use the default ending options or advanced (custom)
     * @type {string}
     * @memberof EndSurveyOptions
     */
    'EndingType': EndSurveyOptionsEndingTypeEnum;
    /**
     * How to mark the response. Default `QuotaMet`
     * @type {string}
     * @memberof EndSurveyOptions
     */
    'ResponseFlag'?: EndSurveyOptionsResponseFlagEnum;
    /**
     * End of survey action such as showing respondents a response summary. See `EOSMessageLibrary`, `EOSMessage`, `ResponseSummary`, and `EOSRedirectURL`.
     * @type {SurveyTermination}
     * @memberof EndSurveyOptions
     */
    'SurveyTermination'?: SurveyTermination | null;
    /**
     * The URL to redirect respondents to at the end of the survey used when `SurveyTermination` is set to `Redirect`.
     * @type {string}
     * @memberof EndSurveyOptions
     */
    'EOSRedirectURL'?: string;
    /**
     * End of survey message library used when `SurveyTermination` is set to `DisplayMessage`. See `SurveyTermination` and `EOSMessage`.
     * @type {string}
     * @memberof EndSurveyOptions
     */
    'EOSMessageLibrary'?: string;
    /**
     * ID of the message to be displayed at the end of the survey
     * @type {string}
     * @memberof EndSurveyOptions
     */
    'EOSMessage'?: string | null;
    /**
     * Send an email thank you message after survey completion
     * @type {EmailThankYou}
     * @memberof EndSurveyOptions
     */
    'EmailThankYou'?: EmailThankYou;
    /**
     * Library ID associated with the Message ID in `ThankYouEmailMessage`.
     * @type {string}
     * @memberof EndSurveyOptions
     */
    'ThankYouEmailMessageLibrary'?: string;
    /**
     * ID of the library message to use for the thank you email. See `EmailThankYou` and `ThankYouEmailMessage`.
     * @type {string}
     * @memberof EndSurveyOptions
     */
    'ThankYouEmailMessage'?: string | null;
    /**
     * Shows the response summary at the end of the survey used when `SurveyTermination` is set to `ResponseSummary`.
     * @type {ResponseSummary}
     * @memberof EndSurveyOptions
     */
    'ResponseSummary'?: ResponseSummary;
    /**
     * Show response summary before completing the survey
     * @type {string}
     * @memberof EndSurveyOptions
     */
    'ConfirmResponseSummary'?: EndSurveyOptionsConfirmResponseSummaryEnum;
    /**
     * The unique identifier for the message library.
     * @type {string}
     * @memberof EndSurveyOptions
     */
    'ConfirmMessageLibrary'?: string;
    /**
     * The unique identifier for the message.
     * @type {string}
     * @memberof EndSurveyOptions
     */
    'ConfirmMessage'?: string;
    /**
     * Yes/No/Empty String.
     * @type {YesNoEmptyString}
     * @memberof EndSurveyOptions
     */
    'CountQuotas'?: YesNoEmptyString;
    /**
     * Yes/No/Empty String.
     * @type {YesNoEmptyString}
     * @memberof EndSurveyOptions
     */
    'Screenout'?: YesNoEmptyString;
    /**
     * 
     * @type {string}
     * @memberof EndSurveyOptions
     */
    'ScreenOutName'?: string;
    /**
     * Yes/No/Empty String.
     * @type {YesNoEmptyString}
     * @memberof EndSurveyOptions
     */
    'AnonymizeResponse'?: YesNoEmptyString;
    /**
     * Yes/No/Empty String.
     * @type {YesNoEmptyString}
     * @memberof EndSurveyOptions
     */
    'IgnoreResponse'?: YesNoEmptyString;
}

type EndSurveyOptionsEndingTypeEnum = 'Default' | 'Advanced'
type EndSurveyOptionsResponseFlagEnum = 'QuotaMet'
type EndSurveyOptionsConfirmResponseSummaryEnum = 'true' | ''


