/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ComparisonOperators } from './comparison-operators';

/**
 * Logic expression for a Evaluator Metadata type
 * @export
 * @interface EvaluatorMetadataExpression
 */
export interface EvaluatorMetadataExpression {
    [key: string]: any;

    /**
     * Logic type of the evaluator metadata expression.
     * @type {string}
     * @memberof EvaluatorMetadataExpression
     */
    'LogicType': EvaluatorMetadataExpressionLogicTypeEnum;
    /**
     * A user-provided description field.
     * @type {string}
     * @memberof EvaluatorMetadataExpression
     */
    'Description': string;
    /**
     * Operation.
     * @type {string}
     * @memberof EvaluatorMetadataExpression
     */
    'LeftOperand': string;
    /**
     * Comparison operators.
     * @type {ComparisonOperators}
     * @memberof EvaluatorMetadataExpression
     */
    'Operator'?: ComparisonOperators;
    /**
     * Person meta data.
     * @type {string}
     * @memberof EvaluatorMetadataExpression
     */
    'PersonMeta': string;
    /**
     * Operation.
     * @type {string}
     * @memberof EvaluatorMetadataExpression
     */
    'RightOperand'?: string;
    /**
     * Same as subject.
     * @type {string}
     * @memberof EvaluatorMetadataExpression
     */
    'SameAsSubjectRightOperand'?: string;
    /**
     * Type of evaluator metadata expression.
     * @type {string}
     * @memberof EvaluatorMetadataExpression
     */
    'Type': EvaluatorMetadataExpressionTypeEnum;
}

type EvaluatorMetadataExpressionLogicTypeEnum = 'EvaluatorMetadata'
type EvaluatorMetadataExpressionTypeEnum = 'Expression'


