/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ComparisonOperators } from './comparison-operators';

/**
 * Logic expression for a Geo IP type.
 * @export
 * @interface GeoIPExpression
 */
export interface GeoIPExpression {
    [key: string]: any;

    /**
     * The logic type of the Geo IP expression.
     * @type {string}
     * @memberof GeoIPExpression
     */
    'LogicType': GeoIPExpressionLogicTypeEnum;
    /**
     * A user-provided description field.
     * @type {string}
     * @memberof GeoIPExpression
     */
    'Description': string;
    /**
     * Operation.
     * @type {string}
     * @memberof GeoIPExpression
     */
    'LeftOperand'?: GeoIPExpressionLeftOperandEnum;
    /**
     * Comparison operators.
     * @type {ComparisonOperators}
     * @memberof GeoIPExpression
     */
    'Operator'?: ComparisonOperators;
    /**
     * Operation.
     * @type {string}
     * @memberof GeoIPExpression
     */
    'RightOperand'?: string;
    /**
     * The type of Geo IP expression.
     * @type {string}
     * @memberof GeoIPExpression
     */
    'Type': GeoIPExpressionTypeEnum;
}

type GeoIPExpressionLogicTypeEnum = 'GeoIP'
type GeoIPExpressionLeftOperandEnum = 'loc://PostalCode' | 'loc://City' | 'loc://Region' | 'loc://AreaCode' | 'loc://CountryName' | 'loc://CountryCode' | 'LocationMap'
type GeoIPExpressionTypeEnum = 'Expression'


