/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Language } from './language';
import { QuestionConfiguration } from './question-configuration';
import { Validation } from './validation';

/**
 * 
 * @export
 * @interface GraphicQuestionDefinition
 */
export interface GraphicQuestionDefinition {
    /**
     * 
     * @type {QuestionConfiguration}
     * @memberof GraphicQuestionDefinition
     */
    'Configuration': QuestionConfiguration;
    /**
     * The tag to identify the question in exported data.
     * @type {string}
     * @memberof GraphicQuestionDefinition
     */
    'DataExportTag': string;
    /**
     * 
     * @type {boolean}
     * @memberof GraphicQuestionDefinition
     */
    'DefaultChoices': boolean;
    /**
     * The unique identifier for the image.
     * @type {string}
     * @memberof GraphicQuestionDefinition
     */
    'Graphics': string;
    /**
     * 
     * @type {string}
     * @memberof GraphicQuestionDefinition
     */
    'GraphicsDescription': string;
    /**
     * 
     * @type {Language}
     * @memberof GraphicQuestionDefinition
     */
    'Language': Language;
    /**
     * 
     * @type {number}
     * @memberof GraphicQuestionDefinition
     */
    'NextAnswerId'?: number;
    /**
     * 
     * @type {number}
     * @memberof GraphicQuestionDefinition
     */
    'NextChoiceId'?: number;
    /**
     * 
     * @type {string}
     * @memberof GraphicQuestionDefinition
     */
    'QuestionDescription': string;
    /**
     * The unique identifier for the question.
     * @type {string}
     * @memberof GraphicQuestionDefinition
     */
    'QuestionID'?: string;
    /**
     * Text for the question.
     * @type {string}
     * @memberof GraphicQuestionDefinition
     */
    'QuestionText': string;
    /**
     * 
     * @type {string}
     * @memberof GraphicQuestionDefinition
     */
    'QuestionType': GraphicQuestionDefinitionQuestionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GraphicQuestionDefinition
     */
    'Selector': GraphicQuestionDefinitionSelectorEnum;
    /**
     * 
     * @type {Validation}
     * @memberof GraphicQuestionDefinition
     */
    'Validation': Validation;
}

type GraphicQuestionDefinitionQuestionTypeEnum = 'DB'
type GraphicQuestionDefinitionSelectorEnum = 'GRB'


