/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ComparisonOperators } from './comparison-operators';

/**
 * Logic expression for a Loop & Merge type.
 * @export
 * @interface LoopAndMergeExpression
 */
export interface LoopAndMergeExpression {
    [key: string]: any;

    /**
     * The logic type of the loop and merge expression.
     * @type {string}
     * @memberof LoopAndMergeExpression
     */
    'LogicType': LoopAndMergeExpressionLogicTypeEnum;
    /**
     * A user-provided description field.
     * @type {string}
     * @memberof LoopAndMergeExpression
     */
    'Description': string;
    /**
     * The ID of the survey\'s default block.
     * @type {string}
     * @memberof LoopAndMergeExpression
     */
    'LeftOperand'?: string;
    /**
     * Comparison operators.
     * @type {ComparisonOperators}
     * @memberof LoopAndMergeExpression
     */
    'Operator'?: ComparisonOperators;
    /**
     * Operation.
     * @type {string}
     * @memberof LoopAndMergeExpression
     */
    'RightOperand'?: LoopAndMergeExpressionRightOperandEnum;
    /**
     * The type of loop and merge expression.
     * @type {string}
     * @memberof LoopAndMergeExpression
     */
    'Type': LoopAndMergeExpressionTypeEnum;
}

type LoopAndMergeExpressionLogicTypeEnum = 'LoopAndMerge'
type LoopAndMergeExpressionRightOperandEnum = 'lm://CurrentLoop' | 'lm://CurrentLoopNumber' | 'lm://CurrentLoopById'
type LoopAndMergeExpressionTypeEnum = 'Expression'


