/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AnswerRandomization } from './answer-randomization';
import { Language } from './language';
import { QuestionChoicesValue } from './question-choices-value';
import { QuestionConfiguration } from './question-configuration';
import { Randomization } from './randomization';
import { Validation } from './validation';

/**
 * 
 * @export
 * @interface MatrixQuestionDefinition
 */
export interface MatrixQuestionDefinition {
    /**
     * The order the choices are to be displayed in.
     * @type {Array<string>}
     * @memberof MatrixQuestionDefinition
     */
    'AnswerOrder': Array<string>;
    /**
     * Selections for a question
     * @type {{ [key: string]: QuestionChoicesValue; }}
     * @memberof MatrixQuestionDefinition
     */
    'Answers': { [key: string]: QuestionChoicesValue; };
    /**
     * 
     * @type {AnswerRandomization}
     * @memberof MatrixQuestionDefinition
     */
    'AnswerRandomization'?: AnswerRandomization;
    /**
     * 
     * @type {boolean}
     * @memberof MatrixQuestionDefinition
     */
    'ChoiceDataExportTags': boolean;
    /**
     * The order the choices are to be displayed in.
     * @type {Array<string>}
     * @memberof MatrixQuestionDefinition
     */
    'ChoiceOrder': Array<string>;
    /**
     * Selections for a question
     * @type {{ [key: string]: QuestionChoicesValue; }}
     * @memberof MatrixQuestionDefinition
     */
    'Choices': { [key: string]: QuestionChoicesValue; };
    /**
     * 
     * @type {QuestionConfiguration}
     * @memberof MatrixQuestionDefinition
     */
    'Configuration': QuestionConfiguration;
    /**
     * The tag to identify the question in exported data.
     * @type {string}
     * @memberof MatrixQuestionDefinition
     */
    'DataExportTag': string;
    /**
     * 
     * @type {boolean}
     * @memberof MatrixQuestionDefinition
     */
    'DefaultChoices': boolean;
    /**
     * 
     * @type {Language}
     * @memberof MatrixQuestionDefinition
     */
    'Language': Language;
    /**
     * 
     * @type {number}
     * @memberof MatrixQuestionDefinition
     */
    'NextAnswerId'?: number;
    /**
     * 
     * @type {number}
     * @memberof MatrixQuestionDefinition
     */
    'NextChoiceId'?: number;
    /**
     * 
     * @type {string}
     * @memberof MatrixQuestionDefinition
     */
    'QuestionDescription': string;
    /**
     * The unique identifier for the question.
     * @type {string}
     * @memberof MatrixQuestionDefinition
     */
    'QuestionID'?: string;
    /**
     * Text for the question.
     * @type {string}
     * @memberof MatrixQuestionDefinition
     */
    'QuestionText': string;
    /**
     * 
     * @type {string}
     * @memberof MatrixQuestionDefinition
     */
    'QuestionType': MatrixQuestionDefinitionQuestionTypeEnum;
    /**
     * 
     * @type {Randomization}
     * @memberof MatrixQuestionDefinition
     */
    'Randomization'?: Randomization;
    /**
     * Numeric mapping of question choices.
     * @type {{ [key: string]: string; }}
     * @memberof MatrixQuestionDefinition
     */
    'RecodeValues'?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof MatrixQuestionDefinition
     */
    'Selector': MatrixQuestionDefinitionSelectorEnum;
    /**
     * 
     * @type {string}
     * @memberof MatrixQuestionDefinition
     */
    'SubSelector': MatrixQuestionDefinitionSubSelectorEnum;
    /**
     * 
     * @type {Validation}
     * @memberof MatrixQuestionDefinition
     */
    'Validation': Validation;
}

type MatrixQuestionDefinitionQuestionTypeEnum = 'Matrix'
type MatrixQuestionDefinitionSelectorEnum = 'Bipolar' | 'Likert' | 'TE' | 'Profile' | 'CS' | 'RO' | 'MaxDiff'
type MatrixQuestionDefinitionSubSelectorEnum = 'DL' | 'DND' | 'Long' | 'Medium' | 'MultipleAnswer' | 'Short' | 'SingleAnswer' | 'WOTB' | 'WTB' | 'WVTB' | 'WTXB' | 'Essay'


