/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ComparisonOperators } from './comparison-operators';

/**
 * Logic expression for a Org Hierarchy Units type.
 * @export
 * @interface OrgHierarchyUnitsExpression
 */
export interface OrgHierarchyUnitsExpression {
    [key: string]: any;

    /**
     * A user-provided description field.
     * @type {string}
     * @memberof OrgHierarchyUnitsExpression
     */
    'Description': string;
    /**
     * The logic type for a Org Hierarchy Units type.
     * @type {string}
     * @memberof OrgHierarchyUnitsExpression
     */
    'LogicType': OrgHierarchyUnitsExpressionLogicTypeEnum;
    /**
     * Comparison operators.
     * @type {ComparisonOperators}
     * @memberof OrgHierarchyUnitsExpression
     */
    'Operator'?: ComparisonOperators;
    /**
     * The unique identifier for the Organization Hierarchy.
     * @type {string}
     * @memberof OrgHierarchyUnitsExpression
     */
    'OrgHierarchyID': string;
    /**
     * The unique identifier for the Org Hierarchy Unit.
     * @type {string}
     * @memberof OrgHierarchyUnitsExpression
     */
    'UnitID'?: string;
    /**
     * The name of the unit.
     * @type {string}
     * @memberof OrgHierarchyUnitsExpression
     */
    'UnitName'?: string;
}

type OrgHierarchyUnitsExpressionLogicTypeEnum = 'OrgHierarchyUnits'


