/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Logic expression for a Org Hierarchy Metadata type.
 * @export
 * @interface OrgHierarchyMetadataExpression
 */
export interface OrgHierarchyMetadataExpression {
    [key: string]: any;

    /**
     * A user-provided description field.
     * @type {string}
     * @memberof OrgHierarchyMetadataExpression
     */
    'Description': string;
    /**
     * Text field for the Org Hierarchy Metadata type.
     * @type {string}
     * @memberof OrgHierarchyMetadataExpression
     */
    'Field'?: string;
    /**
     * The logic type of the Org Hierarchy Metadata type.
     * @type {string}
     * @memberof OrgHierarchyMetadataExpression
     */
    'LogicType': OrgHierarchyMetadataExpressionLogicTypeEnum;
    /**
     * Operator for the Org Hierarchy Metadata type.
     * @type {string}
     * @memberof OrgHierarchyMetadataExpression
     */
    'Operator'?: OrgHierarchyMetadataExpressionOperatorEnum;
    /**
     * Org hierarchy definition.
     * @type {{ [key: string]: any; }}
     * @memberof OrgHierarchyMetadataExpression
     */
    'OrgHierarchyDef'?: { [key: string]: any; };
    /**
     * The unique identifier for the Organization Hierarchy.
     * @type {string}
     * @memberof OrgHierarchyMetadataExpression
     */
    'OrgHierarchyID'?: string;
    /**
     * The type of org hierarchy metadata expression.
     * @type {string}
     * @memberof OrgHierarchyMetadataExpression
     */
    'Type': OrgHierarchyMetadataExpressionTypeEnum;
    /**
     * An attribute associated with `key`.
     * @type {string}
     * @memberof OrgHierarchyMetadataExpression
     */
    'Value'?: string;
}

type OrgHierarchyMetadataExpressionLogicTypeEnum = 'OrgHierarchyMetadata'
type OrgHierarchyMetadataExpressionOperatorEnum = 'ArrayContains'
type OrgHierarchyMetadataExpressionTypeEnum = 'Expression'


