/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ComparisonOperators } from './comparison-operators';

/**
 * Logic expression for a Panel Data type.
 * @export
 * @interface PanelDataExpression
 */
export interface PanelDataExpression {
    [key: string]: any;

    /**
     * A user-provided description field.
     * @type {string}
     * @memberof PanelDataExpression
     */
    'Description': string;
    /**
     * Operation.
     * @type {string}
     * @memberof PanelDataExpression
     */
    'LeftOperand': PanelDataExpressionLeftOperandEnum;
    /**
     * The logic type of the Panel data expression.
     * @type {string}
     * @memberof PanelDataExpression
     */
    'LogicType': PanelDataExpressionLogicTypeEnum;
    /**
     * Comparison operators.
     * @type {ComparisonOperators}
     * @memberof PanelDataExpression
     */
    'Operator'?: ComparisonOperators;
    /**
     * Operation.
     * @type {string}
     * @memberof PanelDataExpression
     */
    'RightOperand'?: string;
    /**
     * The type of the Panel data expression.
     * @type {string}
     * @memberof PanelDataExpression
     */
    'Type': PanelDataExpressionTypeEnum;
}

type PanelDataExpressionLeftOperandEnum = 'm://FirstName' | 'm://LastName' | 'm://ContactPoint' | 'm://ExternalDataReference' | 'm://Email'
type PanelDataExpressionLogicTypeEnum = 'PanelData'
type PanelDataExpressionTypeEnum = 'Expression'


