/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Locator } from './locator';

/**
 * Logic expression for a question type.
 * @export
 * @interface QuestionExpression
 */
export interface QuestionExpression {
    [key: string]: any;

    /**
     * 
     * @type {Locator}
     * @memberof QuestionExpression
     */
    'ChoiceLocator': Locator;
    /**
     * The logic type of a question expression.
     * @type {string}
     * @memberof QuestionExpression
     */
    'LogicType': QuestionExpressionLogicTypeEnum;
    /**
     * Operator.
     * @type {string}
     * @memberof QuestionExpression
     */
    'Operator': QuestionExpressionOperatorEnum;
    /**
     * The unique identifier for the question.
     * @type {string}
     * @memberof QuestionExpression
     */
    'QuestionID': string;
    /**
     * If yes, question is in loop.
     * @type {string}
     * @memberof QuestionExpression
     */
    'QuestionIsInLoop': QuestionExpressionQuestionIsInLoopEnum;
    /**
     * The type of question expression.
     * @type {string}
     * @memberof QuestionExpression
     */
    'Type': QuestionExpressionTypeEnum;
}

type QuestionExpressionLogicTypeEnum = 'Question'
type QuestionExpressionOperatorEnum = 'Selected' | 'NotSelected' | 'EqualTo' | 'NotEqualTo' | 'Empty' | 'NotEmpty' | 'Displayed' | 'NotDisplayed' | 'GreaterThan' | 'GreaterThanOrEqual' | 'LessThan' | 'LessThanOrEqual' | 'Contains' | 'DoesNotContain' | 'MatchesRegex' | 'IsNot' | 'Uploaded' | 'NotUploaded' | 'PDF' | 'Document' | 'ClickedIn' | 'NotClickedIn' | 'Extensions' | 'Graphic' | 'Spreadsheet'
type QuestionExpressionQuestionIsInLoopEnum = 'true' | 'false'
type QuestionExpressionTypeEnum = 'Expression'


