/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Configurations for how the question should be displayed
 * @export
 * @interface QuestionConfiguration
 */
export interface QuestionConfiguration {
    [key: string]: any;

    /**
     * An optional user-provided field for question descriptions.
     * @type {string}
     * @memberof QuestionConfiguration
     */
    'QuestionDescriptionOption'?: QuestionConfigurationQuestionDescriptionOptionEnum;
    /**
     * Text position.
     * @type {string}
     * @memberof QuestionConfiguration
     */
    'TextPosition'?: QuestionConfigurationTextPositionEnum;
    /**
     * Value of column width.
     * @type {number}
     * @memberof QuestionConfiguration
     */
    'ChoiceColumnWidth'?: QuestionConfigurationChoiceColumnWidthEnum;
    /**
     * Repeating of headers.
     * @type {string}
     * @memberof QuestionConfiguration
     */
    'RepeatHeaders'?: QuestionConfigurationRepeatHeadersEnum;
    /**
     * If white space is allowed.
     * @type {string}
     * @memberof QuestionConfiguration
     */
    'WhiteSpace'?: QuestionConfigurationWhiteSpaceEnum;
    /**
     * Position of label.
     * @type {string}
     * @memberof QuestionConfiguration
     */
    'LabelPosition'?: QuestionConfigurationLabelPositionEnum;
    /**
     * Number of columns.
     * @type {number}
     * @memberof QuestionConfiguration
     */
    'NumColumns'?: number;
    /**
     * If questions should be formatted for use on a mobile device.
     * @type {boolean}
     * @memberof QuestionConfiguration
     */
    'MobileFirst'?: boolean;
}

type QuestionConfigurationQuestionDescriptionOptionEnum = 'UseText' | 'SpecifyLabel'
type QuestionConfigurationTextPositionEnum = 'inline'
type QuestionConfigurationChoiceColumnWidthEnum = 25
type QuestionConfigurationRepeatHeadersEnum = 'none'
type QuestionConfigurationWhiteSpaceEnum = 'true' | 'false'
type QuestionConfigurationLabelPositionEnum = 'BELOW' | 'SIDE'


