/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CrossLogicDefEntry } from './cross-logic-def-entry';
import { EndSurveyOptions } from './end-survey-options';
import { QuotaAction } from './quota-action';
import { QuotaActionElement } from './quota-action-element';
import { QuotaLogic } from './quota-logic';
import { QuotaLogicType } from './quota-logic-type';
import { QuotaSchedule } from './quota-schedule';
import { WebServiceOptions } from './web-service-options';

/**
 * Keep track of how many respondents meet a condition in the survey
 * @export
 * @interface Quota
 */
export interface Quota {
    /**
     * Quota Name
     * @type {string}
     * @memberof Quota
     */
    'Name': string;
    /**
     * Quota Limit. Default: 100
     * @type {number}
     * @memberof Quota
     */
    'Occurrences': number;
    /**
     * Quota Count. Default: 0
     * @type {number}
     * @memberof Quota
     */
    'Count'?: number;
    /**
     * For restoring quota count
     * @type {number}
     * @memberof Quota
     */
    'CountForUndo'?: number;
    /**
     * 
     * @type {QuotaLogic}
     * @memberof Quota
     */
    'Logic': QuotaLogic;
    /**
     * 
     * @type {QuotaLogicType}
     * @memberof Quota
     */
    'LogicType'?: QuotaLogicType;
    /**
     * Specify the action to take once the quota has been met for the respondent. Default: `EndCurrentSurvey`. See `ActionInfo` and `ActionElement`
     * @type {QuotaAction}
     * @memberof Quota
     */
    'QuotaAction': QuotaAction;
    /**
     * 
     * @type {QuotaActionElement}
     * @memberof Quota
     */
    'ActionElement'?: QuotaActionElement;
    /**
     * Additional info for `QuotaAction`. See `QuotaAction`
     * @type {{ [key: string]: any; }}
     * @memberof Quota
     */
    'ActionInfo'?: { [key: string]: any; };
    /**
     * Additional info for `QuotaAction`. See `QuotaAction`
     * @type {{ [key: string]: any; }}
     * @memberof Quota
     */
    'ActionLogic'?: { [key: string]: any; };
    /**
     * The unique identifier for the quota.
     * @type {string}
     * @memberof Quota
     */
    'ID': string;
    /**
     * One of Survey or ResponseSet
     * @type {string}
     * @memberof Quota
     */
    'QuotaRealm': QuotaQuotaRealmEnum;
    /**
     * 
     * @type {QuotaSchedule}
     * @memberof Quota
     */
    'QuotaSchedule'?: QuotaSchedule;
    /**
     * 
     * @type {EndSurveyOptions}
     * @memberof Quota
     */
    'EndSurveyOptions'?: EndSurveyOptions;
    /**
     * 
     * @type {WebServiceOptions}
     * @memberof Quota
     */
    'WebServiceOptions'?: WebServiceOptions;
    /**
     * Definition for the cross logic quota
     * @type {Array<CrossLogicDefEntry>}
     * @memberof Quota
     */
    'CrossLogicDef'?: Array<CrossLogicDefEntry>;
    /**
     * 
     * @type {boolean}
     * @memberof Quota
     */
    'PerformActionOnUser'?: boolean;
}

type QuotaQuotaRealmEnum = 'Survey' | 'ResponseSet'


