/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Logic expression for a quota type.
 * @export
 * @interface QuotaExpression
 */
export interface QuotaExpression {
    [key: string]: any;

    /**
     * The logic type of the quota expression.
     * @type {string}
     * @memberof QuotaExpression
     */
    'LogicType': QuotaExpressionLogicTypeEnum;
    /**
     * A user-provided description field.
     * @type {string}
     * @memberof QuotaExpression
     */
    'Description': string;
    /**
     * Operator.
     * @type {string}
     * @memberof QuotaExpression
     */
    'LeftOperand': string;
    /**
     * Operator.
     * @type {string}
     * @memberof QuotaExpression
     */
    'Operator'?: QuotaExpressionOperatorEnum;
    /**
     * The unique identifier for the quota.
     * @type {string}
     * @memberof QuotaExpression
     */
    'QuotaID': string;
    /**
     * The name of the quota.
     * @type {string}
     * @memberof QuotaExpression
     */
    'QuotaName'?: string;
    /**
     * The type of quota.
     * @type {string}
     * @memberof QuotaExpression
     */
    'QuotaType': QuotaExpressionQuotaTypeEnum;
    /**
     * A unique identifier for the `SubQuotaID`.
     * @type {string}
     * @memberof QuotaExpression
     */
    'SubQuotaID'?: string;
    /**
     * The type of quota expression.
     * @type {string}
     * @memberof QuotaExpression
     */
    'Type': QuotaExpressionTypeEnum;
}

type QuotaExpressionLogicTypeEnum = 'Quota'
type QuotaExpressionOperatorEnum = 'QuotaMet' | 'QuotaNotMet' | 'GreaterThan' | 'GreaterThanOrEqual' | 'LessThan' | 'LessThanOrEqual' | 'EqualTo' | 'NotEqualTo'
type QuotaExpressionQuotaTypeEnum = 'Simple' | 'Cross' | 'NoLogic'
type QuotaExpressionTypeEnum = 'Expression'


