/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Survey definition for Quota Groups
 * @export
 * @interface QuotaGroup
 */
export interface QuotaGroup {
    /**
     * The unique identifier of the Quota Group.
     * @type {string}
     * @memberof QuotaGroup
     */
    'ID': string;
    /**
     * The unique identifier of the Quota Group.
     * @type {string}
     * @memberof QuotaGroup
     */
    'Id'?: string;
    /**
     * Determines behavior when a single response matches multiple quotas within the group. One of `PlaceInAll`, `LeastFilled`, `MostFilled`, `LeastFilledPercent`, `MostFilledPercent`, `ReverseOrder`, or `CurrentDefinedOrder`
     * @type {string}
     * @memberof QuotaGroup
     */
    'MultipleMatch'?: QuotaGroupMultipleMatchEnum;
    /**
     * Name of the quota group
     * @type {string}
     * @memberof QuotaGroup
     */
    'Name'?: string;
    /**
     * `Public` refers to whether or not the Public Quota Dashboard is enabled. Enabling the Public Quota Dashboard will provide a public page where anyone can view the quotas in that group.
     * @type {boolean}
     * @memberof QuotaGroup
     */
    'Public'?: boolean;
    /**
     * A list of all the quotas in the group
     * @type {Array<string>}
     * @memberof QuotaGroup
     */
    'Quotas'?: Array<string>;
    /**
     * Input will not be persisted. It is only used by the Quota Editor UI
     * @type {boolean}
     * @memberof QuotaGroup
     */
    'Selected'?: boolean;
}

type QuotaGroupMultipleMatchEnum = 'PlaceInAll' | 'LeastFilled' | 'MostFilled' | 'LeastFilledPercent' | 'MostFilledPercent' | 'ReverseOrder' | 'CurrentDefinedOrder'


