/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Reference survey flow element.
 * @export
 * @interface ReferenceSurveyFlowElement
 */
export interface ReferenceSurveyFlowElement {
    [key: string]: any;

    /**
     * The type of reference survey flow element.
     * @type {string}
     * @memberof ReferenceSurveyFlowElement
     */
    'Type'?: ReferenceSurveyFlowElementTypeEnum;
    /**
     * The unique identifier for the survey library.
     * @type {string}
     * @memberof ReferenceSurveyFlowElement
     */
    'ID'?: string;
    /**
     * Unique identifier. Should be of form `FL_1`
     * @type {string}
     * @memberof ReferenceSurveyFlowElement
     */
    'FlowID'?: string;
    /**
     * A user-provided description of the reference survey flow element.
     * @type {string}
     * @memberof ReferenceSurveyFlowElement
     */
    'Description'?: string;
    /**
     * The unique identifier for the group.
     * @type {string}
     * @memberof ReferenceSurveyFlowElement
     */
    'LibraryID'?: string;
}

type ReferenceSurveyFlowElementTypeEnum = 'ReferenceSurvey'


