/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BlockElementsInner } from './block-elements-inner';
import { BlockOptions } from './block-options';
import { LibraryID } from './library-id';

/**
 * Saved survey in the library that can be referenced by other surveys
 * @export
 * @interface ReferenceBlock
 */
export interface ReferenceBlock {
    [key: string]: any;

    /**
     * 
     * @type {Array<Array<BlockElementsInner>>}
     * @memberof ReferenceBlock
     */
    'BlockElements'?: Array<Array<BlockElementsInner>> | null;
    /**
     * 
     * @type {string}
     * @memberof ReferenceBlock
     */
    'Type': ReferenceBlockTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ReferenceBlock
     */
    'SubType': ReferenceBlockSubTypeEnum;
    /**
     * The ID of the survey\'s default block.
     * @type {string}
     * @memberof ReferenceBlock
     */
    'ID': string;
    /**
     * 
     * @type {string}
     * @memberof ReferenceBlock
     */
    'Description': string | null;
    /**
     * 
     * @type {LibraryID}
     * @memberof ReferenceBlock
     */
    'LibraryID': LibraryID;
    /**
     * The unique identifier for the Reference Block.
     * @type {string}
     * @memberof ReferenceBlock
     */
    'ReferencedBlockID': string;
    /**
     * 
     * @type {BlockOptions}
     * @memberof ReferenceBlock
     */
    'Options'?: BlockOptions;
}

type ReferenceBlockTypeEnum = 'Standard'
type ReferenceBlockSubTypeEnum = 'Reference'


