/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ComparisonOperators } from './comparison-operators';

/**
 * Logic expression for a relationship type.
 * @export
 * @interface RelationshipExpression
 */
export interface RelationshipExpression {
    [key: string]: any;

    /**
     * A user-provided description field
     * @type {string}
     * @memberof RelationshipExpression
     */
    'Description': string;
    /**
     * Operation.
     * @type {string}
     * @memberof RelationshipExpression
     */
    'LeftOperand': RelationshipExpressionLeftOperandEnum;
    /**
     * The logic type of the relationship expression.
     * @type {string}
     * @memberof RelationshipExpression
     */
    'LogicType': RelationshipExpressionLogicTypeEnum;
    /**
     * Comparison operators.
     * @type {ComparisonOperators}
     * @memberof RelationshipExpression
     */
    'Operator'?: ComparisonOperators;
    /**
     * Operation.
     * @type {string}
     * @memberof RelationshipExpression
     */
    'RightOperand'?: string;
    /**
     * The type of relationship expression.
     * @type {string}
     * @memberof RelationshipExpression
     */
    'Type': RelationshipExpressionTypeEnum;
}

type RelationshipExpressionLeftOperandEnum = 'e://Field/Relationship'
type RelationshipExpressionLogicTypeEnum = 'Relationship'
type RelationshipExpressionTypeEnum = 'Expression'


