/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BlockElementsInner } from './block-elements-inner';

/**
 * A logical grouping of questions, split by pages, with configuration on how to control the flow and visibility of each question. The original block\'s type is \"Default\"
 * @export
 * @interface StandardBlock
 */
export interface StandardBlock {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof StandardBlock
     */
    'Type': StandardBlockTypeEnum;
    /**
     * All of the elements contained by the block
     * @type {Array<BlockElementsInner>}
     * @memberof StandardBlock
     */
    'BlockElements'?: Array<BlockElementsInner>;
    /**
     * The ID of the survey\'s default block.
     * @type {string}
     * @memberof StandardBlock
     */
    'ID'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardBlock
     */
    'Description': string;
}

type StandardBlockTypeEnum = 'Standard' | 'Default'


