/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ComparisonOperators } from './comparison-operators';

/**
 * Logic expression for a Subject Metadata type
 * @export
 * @interface SubjectMetadataExpression
 */
export interface SubjectMetadataExpression {
    [key: string]: any;

    /**
     * The logic type of the expression.
     * @type {string}
     * @memberof SubjectMetadataExpression
     */
    'LogicType': SubjectMetadataExpressionLogicTypeEnum;
    /**
     * A user-provided description field.
     * @type {string}
     * @memberof SubjectMetadataExpression
     */
    'Description': string;
    /**
     * 
     * @type {string}
     * @memberof SubjectMetadataExpression
     */
    'LeftOperand': string;
    /**
     * Comparison operators.
     * @type {ComparisonOperators}
     * @memberof SubjectMetadataExpression
     */
    'Operator'?: ComparisonOperators;
    /**
     * Personal metadata.
     * @type {string}
     * @memberof SubjectMetadataExpression
     */
    'PersonMeta': string;
    /**
     * Operation.
     * @type {string}
     * @memberof SubjectMetadataExpression
     */
    'RightOperand'?: string;
    /**
     * The type of expression.
     * @type {string}
     * @memberof SubjectMetadataExpression
     */
    'Type': SubjectMetadataExpressionTypeEnum;
}

type SubjectMetadataExpressionLogicTypeEnum = 'SubjectMetadata'
type SubjectMetadataExpressionTypeEnum = 'Expression'


