/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BlockDefinition } from './block-definition';
import { FlowDefinition } from './flow-definition';
import { ProjectInfoDefinition } from './project-info-definition';
import { QuestionDefinition } from './question-definition';
import { ScoringDefinition } from './scoring-definition';
import { SurveyOptions } from './survey-options';
import { SurveyStatus } from './survey-status';

/**
 * 
 * @export
 * @interface SurveyDefinition
 */
export interface SurveyDefinition {
    [key: string]: any;

    /**
     * Number of questions in the survey
     * @type {string}
     * @memberof SurveyDefinition
     */
    'QuestionCount'?: string;
    /**
     * 
     * @type {SurveyOptions}
     * @memberof SurveyDefinition
     */
    'SurveyOptions': SurveyOptions;
    /**
     * The [unique identifier](https://api.qualtrics.com/ZG9jOjg3NjYzNQ-finding-your-qualtrics-i-ds) for this survey.
     * @type {string}
     * @memberof SurveyDefinition
     */
    'SurveyID': string;
    /**
     * 
     * @type {string}
     * @memberof SurveyDefinition
     */
    'SurveyName': string;
    /**
     * The distribution status of the survey, or a flag indicating that it\'s a library block
     * @type {SurveyStatus}
     * @memberof SurveyDefinition
     */
    'SurveyStatus': SurveyStatus;
    /**
     * 
     * @type {string}
     * @memberof SurveyDefinition
     */
    'LastModified': string;
    /**
     * 
     * @type {string}
     * @memberof SurveyDefinition
     */
    'BrandID': string;
    /**
     * The unique identifier for a specific user.
     * @type {string}
     * @memberof SurveyDefinition
     */
    'OwnerID': string;
    /**
     * The unique identifier for the Division ID.
     * @type {string}
     * @memberof SurveyDefinition
     */
    'DivisionID'?: string;
    /**
     * The date the survey was last accessed 
     * @type {string}
     * @memberof SurveyDefinition
     */
    'LastAccessed': string;
    /**
     * The unique identifier for a specific user.
     * @type {string}
     * @memberof SurveyDefinition
     */
    'CreatorID': string;
    /**
     * 
     * @type {string}
     * @memberof SurveyDefinition
     */
    'LastActivated': string;
    /**
     * Survey questions.
     * @type {{ [key: string]: QuestionDefinition; }}
     * @memberof SurveyDefinition
     */
    'Questions': { [key: string]: QuestionDefinition; };
    /**
     * Survey blocks.
     * @type {{ [key: string]: BlockDefinition; }}
     * @memberof SurveyDefinition
     */
    'Blocks': { [key: string]: BlockDefinition; };
    /**
     * Survey response sets.
     * @type {{ [key: string]: string; }}
     * @memberof SurveyDefinition
     */
    'ResponseSets': { [key: string]: string; };
    /**
     * 
     * @type {FlowDefinition}
     * @memberof SurveyDefinition
     */
    'SurveyFlow': FlowDefinition;
    /**
     * 
     * @type {ScoringDefinition}
     * @memberof SurveyDefinition
     */
    'Scoring': ScoringDefinition;
    /**
     * 
     * @type {ProjectInfoDefinition}
     * @memberof SurveyDefinition
     */
    'ProjectInfo': ProjectInfoDefinition;
    /**
     * 
     * @type {string}
     * @memberof SurveyDefinition
     */
    'BrandBaseURL': string;
}

