/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AnonymizeResponse } from './anonymize-response';
import { BallotBoxStuffingPreventionBehavior } from './ballot-box-stuffing-prevention-behavior';
import { CollectGeoLocation } from './collect-geo-location';
import { CustomLanguagesValue } from './custom-languages-value';
import { EmailThankYou } from './email-thank-you';
import { InactiveSurvey } from './inactive-survey';
import { LanguageCode } from './language-code';
import { NoIndex } from './no-index';
import { PageTransition } from './page-transition';
import { PartialData } from './partial-data';
import { PartialDataCloseAfter } from './partial-data-close-after';
import { PasswordProtection } from './password-protection';
import { ProgressBarDisplay } from './progress-bar-display';
import { RecaptchaV3 } from './recaptcha-v3';
import { RefererCheck } from './referer-check';
import { ResponseSummary } from './response-summary';
import { SecureResponseFiles } from './secure-response-files';
import { Skin } from './skin';
import { SurveyExpiration } from './survey-expiration';
import { SurveyProtection } from './survey-protection';
import { SurveyTermination } from './survey-termination';
import { ValidateMessage } from './validate-message';

/**
 * 
 * @export
 * @interface SurveyOptions
 */
export interface SurveyOptions {
    [key: string]: any;

    /**
     * Scrub all respondent identifying information such as IP or location data.
     * @type {AnonymizeResponse}
     * @memberof SurveyOptions
     */
    'AnonymizeResponse'?: AnonymizeResponse;
    /**
     * If true, provide autofocus for questions.
     * @type {boolean}
     * @memberof SurveyOptions
     */
    'Autofocus'?: boolean;
    /**
     * Enables autoadvance on questions
     * @type {boolean}
     * @memberof SurveyOptions
     */
    'Autoadvance'?: boolean;
    /**
     * Enables autoadvance on pages. This requires `Autoadvance` to be anbled as well
     * @type {boolean}
     * @memberof SurveyOptions
     */
    'AutoadvancePages'?: boolean;
    /**
     * The languages the survey supports.
     * @type {{ [key: string]: Array<string>; }}
     * @memberof SurveyOptions
     */
    'AvailableLanguages'?: { [key: string]: Array<string>; };
    /**
     * If true, display the back button
     * @type {boolean}
     * @memberof SurveyOptions
     */
    'BackButton': boolean;
    /**
     * If true, prevent respondents from taking the survey multiple times.
     * @type {boolean}
     * @memberof SurveyOptions
     */
    'BallotBoxStuffingPrevention': boolean;
    /**
     * Ballot box stuffing prevention behavior.
     * @type {BallotBoxStuffingPreventionBehavior}
     * @memberof SurveyOptions
     */
    'BallotBoxStuffingPreventionBehavior'?: BallotBoxStuffingPreventionBehavior | null;
    /**
     * ID of the library message shown to prevent ballot box stuffing. See `BallotBoxStuffingPrevention` and `BallotBoxStuffingPreventionMessageLibrary`.
     * @type {string}
     * @memberof SurveyOptions
     */
    'BallotBoxStuffingPreventionMessage'?: string | null;
    /**
     * Library ID associated with the Message ID in `BallotBoxStuffingPreventionMessage`.
     * @type {string}
     * @memberof SurveyOptions
     */
    'BallotBoxStuffingPreventionMessageLibrary'?: string;
    /**
     * Ballot Box stuffing prevention URL.
     * @type {string}
     * @memberof SurveyOptions
     */
    'BallotBoxStuffingPreventionURL'?: string;
    /**
     * Collect respondents Geo Location. Default `false`.
     * @type {CollectGeoLocation}
     * @memberof SurveyOptions
     */
    'CollectGeoLocation'?: CollectGeoLocation;
    /**
     * Custom CSS to load when survey taking. See also `ExternalCSS`.
     * @type {string}
     * @memberof SurveyOptions
     */
    'CustomStyles'?: string;
    /**
     * The custom languages the survey supports.
     * @type {{ [key: string]: CustomLanguagesValue; }}
     * @memberof SurveyOptions
     */
    'CustomLanguages'?: { [key: string]: CustomLanguagesValue; };
    /**
     * Send an email thank you message after survey completion
     * @type {EmailThankYou}
     * @memberof SurveyOptions
     */
    'EmailThankYou'?: EmailThankYou;
    /**
     * ID of the message to be displayed at the end of the survey
     * @type {string}
     * @memberof SurveyOptions
     */
    'EOSMessage'?: string | null;
    /**
     * The URL to redirect respondents to at the end of the survey used when `SurveyTermination` is set to `Redirect`.
     * @type {string}
     * @memberof SurveyOptions
     */
    'EOSRedirectURL'?: string;
    /**
     * CSS URL to load when survey taking. See also `CustomStyles`.
     * @type {string}
     * @memberof SurveyOptions
     */
    'ExternalCSS'?: string;
    /**
     * ID of the library message to display in the header. Do not use in conjunction with `Header`.
     * @type {string}
     * @memberof SurveyOptions
     */
    'headerMid'?: string | null;
    /**
     * Header to display on each page such as a logo. Do not use in conjunction with `headerMid`.
     * @type {string}
     * @memberof SurveyOptions
     */
    'Header': string;
    /**
     * ID of the library message to display in the footer. Do not use in conjunction with `Footer`.
     * @type {string}
     * @memberof SurveyOptions
     */
    'footerMid'?: string | null;
    /**
     * Footer to display on each page such as a logo. Do not use in conjunction with `footerMid`.
     * @type {string}
     * @memberof SurveyOptions
     */
    'Footer': string;
    /**
     * Whether or not to use a custom validation message. See `InactiveMessage` and `InactiveMessageLibrary`.
     * @type {InactiveSurvey}
     * @memberof SurveyOptions
     */
    'InactiveSurvey'?: InactiveSurvey | null;
    /**
     * ID of the library message to use when `InactiveSurvey` is set to `DisplayMessage`. See `InactiveSurvey` and `InactiveMessageLibrary`.
     * @type {string}
     * @memberof SurveyOptions
     */
    'InactiveMessage'?: string | null;
    /**
     * Library ID associated with the Message ID in `InactiveMessage`.
     * @type {string}
     * @memberof SurveyOptions
     */
    'InactiveMessageLibrary'?: string;
    /**
     * Prevent search engines from indexing the survey.
     * @type {NoIndex}
     * @memberof SurveyOptions
     */
    'NoIndex': NoIndex;
    /**
     * ID of the library message to display in the \"next\" button. Do not use in conjunction with `NextButton`.
     * @type {string}
     * @memberof SurveyOptions
     */
    'nextButtonMid'?: string | null;
    /**
     * The text to use as the \"next\" Button. Note that `BackButton` should be enabled for this property to be used. See `nextButtonMid` and `BackButton`.
     * @type {string}
     * @memberof SurveyOptions
     */
    'NextButton': string;
    /**
     * Transition between page navigation.
     * @type {PageTransition}
     * @memberof SurveyOptions
     */
    'PageTransition'?: PageTransition;
    /**
     * Specify how long a respondent can leave a survey unfinished before that survey automatically closes. A value of `No` specifies to delete partial completion data. See also `PartialDataCloseAfter`.
     * @type {PartialData}
     * @memberof SurveyOptions
     */
    'PartialData': PartialData;
    /**
     * When the partial data deadline starts, either by LastActivity or SurveyStart. See `PartialData`.
     * @type {PartialDataCloseAfter}
     * @memberof SurveyOptions
     */
    'PartialDataCloseAfter'?: PartialDataCloseAfter;
    /**
     * The password to take the survey. See `PasswordProtection`.
     * @type {string}
     * @memberof SurveyOptions
     */
    'Password'?: string;
    /**
     * Require a password to take the survey. See `Password`.
     * @type {PasswordProtection}
     * @memberof SurveyOptions
     */
    'PasswordProtection'?: PasswordProtection | null;
    /**
     * ID of the library message to display in the \"previous\" button. Do not use in conjunction with `PreviousButton`.
     * @type {string}
     * @memberof SurveyOptions
     */
    'previousButtonMid'?: string | null;
    /**
     * The text to use as the \"previous\" Button. Note that `BackButton` should be enabled for this property to be used. See `previousButtonMid` and `BackButton`.
     * @type {string}
     * @memberof SurveyOptions
     */
    'PreviousButton': string;
    /**
     * Shows participants a progress bar.
     * @type {ProgressBarDisplay}
     * @memberof SurveyOptions
     */
    'ProgressBarDisplay': ProgressBarDisplay;
    /**
     * Number of questions to display per page.
     * @type {string}
     * @memberof SurveyOptions
     */
    'QuestionsPerPage'?: string;
    /**
     * Apply bot detection on the survey taking experience.
     * @type {RecaptchaV3}
     * @memberof SurveyOptions
     */
    'RecaptchaV3'?: RecaptchaV3;
    /**
     * Whether or not to restrict the URL respondents must come from to access the survey. See `RefererURL`.
     * @type {RefererCheck}
     * @memberof SurveyOptions
     */
    'RefererCheck'?: RefererCheck;
    /**
     * The URL respondents must come from to access the survey. See `RefererCheck`.
     * @type {string}
     * @memberof SurveyOptions
     */
    'RefererURL'?: string;
    /**
     * Shows the response summary at the end of the survey used when `SurveyTermination` is set to `ResponseSummary`.
     * @type {ResponseSummary}
     * @memberof SurveyOptions
     */
    'ResponseSummary'?: ResponseSummary;
    /**
     * If true, allow respondents to save and continue later.
     * @type {boolean}
     * @memberof SurveyOptions
     */
    'SaveAndContinue': boolean;
    /**
     * If true, uploaded files by respondents can only be viewed by the survey owner.
     * @type {SecureResponseFiles}
     * @memberof SurveyOptions
     */
    'SecureResponseFiles': SecureResponseFiles;
    /**
     * 
     * @type {Skin}
     * @memberof SurveyOptions
     */
    'Skin': Skin;
    /**
     * Sets the survey to be available during a specified time period. See `SurveyStartDate` and `SurveyExpirationDate`.
     * @type {SurveyExpiration}
     * @memberof SurveyOptions
     */
    'SurveyExpiration': SurveyExpiration | null;
    /**
     * When respondents can no longer take the survey.
     * @type {string}
     * @memberof SurveyOptions
     */
    'SurveyExpirationDate'?: string | null;
    /**
     * Meta description for the survey, used by search engines and so forth.
     * @type {string}
     * @memberof SurveyOptions
     */
    'SurveyMetaDescription'?: string;
    /**
     * The default language of the survey.
     * @type {LanguageCode}
     * @memberof SurveyOptions
     */
    'SurveyLanguage'?: LanguageCode;
    /**
     * Name of the survey
     * @type {string}
     * @memberof SurveyOptions
     */
    'SurveyName'?: string;
    /**
     * Survey is either publicly available or restricted by invitation only
     * @type {SurveyProtection}
     * @memberof SurveyOptions
     */
    'SurveyProtection': SurveyProtection;
    /**
     * When respondents can start taking the survey
     * @type {string}
     * @memberof SurveyOptions
     */
    'SurveyStartDate'?: string | null;
    /**
     * End of survey action such as showing respondents a response summary. See `EOSMessageLibrary`, `EOSMessage`, `ResponseSummary`, and `EOSRedirectURL`.
     * @type {SurveyTermination}
     * @memberof SurveyOptions
     */
    'SurveyTermination': SurveyTermination | null;
    /**
     * Title of the survey, displayed to users on the browser window/tab.
     * @type {string}
     * @memberof SurveyOptions
     */
    'SurveyTitle'?: string;
    /**
     * ID of the library message to use for the thank you email. See `EmailThankYou` and `ThankYouEmailMessage`.
     * @type {string}
     * @memberof SurveyOptions
     */
    'ThankYouEmailMessage'?: string | null;
    /**
     * Library ID associated with the Message ID in `ThankYouEmailMessage`.
     * @type {string}
     * @memberof SurveyOptions
     */
    'ThankYouEmailMessageLibrary'?: string;
    /**
     * Whether or not to use a custom validation message. See `ValidationMessage` and `ValidationMessageLibrary`.
     * @type {ValidateMessage}
     * @memberof SurveyOptions
     */
    'ValidateMessage'?: ValidateMessage;
    /**
     * ID of the library message to use for the custom validation message. See `ValidateMessage` and `ValidationMessageLibrary`.
     * @type {string}
     * @memberof SurveyOptions
     */
    'ValidationMessage': string | null;
    /**
     * Library ID associated with the Message ID in `ValidationMessage`.
     * @type {string}
     * @memberof SurveyOptions
     */
    'ValidationMessageLibrary'?: string;
}

