/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PublishEvent } from './publish-event';

/**
 * 
 * @export
 * @interface SurveyVersionMetadata
 */
export interface SurveyVersionMetadata {
    /**
     * A user-provided description of the survey version.
     * @type {string}
     * @memberof SurveyVersionMetadata
     */
    'description': string;
    /**
     * The [unique identifier](https://api.qualtrics.com/ZG9jOjg3NjYzNQ-finding-your-qualtrics-i-ds) for this survey.
     * @type {string}
     * @memberof SurveyVersionMetadata
     */
    'surveyID': string;
    /**
     * The unique identifier for this survey version.
     * @type {string}
     * @memberof SurveyVersionMetadata
     */
    'versionID': string;
    /**
     * The version number of this survey.
     * @type {number}
     * @memberof SurveyVersionMetadata
     */
    'versionNumber': number;
    /**
     * The unique identifier for a specific user.
     * @type {string}
     * @memberof SurveyVersionMetadata
     */
    'userID': string;
    /**
     * The creation date of survey version expressed as an [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) value.
     * @type {string}
     * @memberof SurveyVersionMetadata
     */
    'creationDate': string;
    /**
     * When true, publish the new version.
     * @type {boolean}
     * @memberof SurveyVersionMetadata
     */
    'published': boolean;
    /**
     * Filter surveys by the publication status.
     * @type {boolean}
     * @memberof SurveyVersionMetadata
     */
    'wasPublished': boolean;
    /**
     * 
     * @type {Array<PublishEvent>}
     * @memberof SurveyVersionMetadata
     */
    'publishEvents': Array<PublishEvent>;
}

