/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FlowInner } from './flow-inner';
import { TableOfContentsFlowElementOptions } from './table-of-contents-flow-element-options';

/**
 * The table of contents flow element.
 * @export
 * @interface TableOfContentsFlowElement
 */
export interface TableOfContentsFlowElement {
    [key: string]: any;

    /**
     * The type of table of contents flow element.
     * @type {string}
     * @memberof TableOfContentsFlowElement
     */
    'Type'?: TableOfContentsFlowElementTypeEnum;
    /**
     * Unique identifier. Should be of form `FL_1`
     * @type {string}
     * @memberof TableOfContentsFlowElement
     */
    'FlowID'?: string;
    /**
     * A user-provided description of the table of contents flow element.
     * @type {string}
     * @memberof TableOfContentsFlowElement
     */
    'Description'?: string;
    /**
     * 
     * @type {TableOfContentsFlowElementOptions}
     * @memberof TableOfContentsFlowElement
     */
    'Options'?: TableOfContentsFlowElementOptions;
    /**
     * Definition of the inner flow elements (maximum of 5000)
     * @type {Array<FlowInner>}
     * @memberof TableOfContentsFlowElement
     */
    'Flow'?: Array<FlowInner>;
}

type TableOfContentsFlowElementTypeEnum = 'TableOfContents'


