/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Options for the table of contents flow element.
 * @export
 * @interface TableOfContentsFlowElementOptions
 */
export interface TableOfContentsFlowElementOptions {
    [key: string]: any;

    /**
     * If `Yes`, show sidebar.
     * @type {string}
     * @memberof TableOfContentsFlowElementOptions
     */
    'ShowSidebar'?: TableOfContentsFlowElementOptionsShowSidebarEnum;
    /**
     * If `Yes`, show table of contents conclusion.
     * @type {string}
     * @memberof TableOfContentsFlowElementOptions
     */
    'TocConclusion'?: TableOfContentsFlowElementOptionsTocConclusionEnum;
}

type TableOfContentsFlowElementOptionsShowSidebarEnum = 'true' | 'false'
type TableOfContentsFlowElementOptionsTocConclusionEnum = 'true' | 'false'


