/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Language } from './language';
import { QuestionConfiguration } from './question-configuration';
import { QuestionType } from './question-type';
import { Validation } from './validation';

/**
 * 
 * @export
 * @interface TextEntryQuestionDefinition
 */
export interface TextEntryQuestionDefinition {
    /**
     * 
     * @type {QuestionConfiguration}
     * @memberof TextEntryQuestionDefinition
     */
    'Configuration': QuestionConfiguration;
    /**
     * The tag to identify the question in exported data.
     * @type {string}
     * @memberof TextEntryQuestionDefinition
     */
    'DataExportTag': string;
    /**
     * 
     * @type {boolean}
     * @memberof TextEntryQuestionDefinition
     */
    'DefaultChoices': boolean;
    /**
     * 
     * @type {Language}
     * @memberof TextEntryQuestionDefinition
     */
    'Language': Language;
    /**
     * 
     * @type {number}
     * @memberof TextEntryQuestionDefinition
     */
    'NextAnswerId'?: number;
    /**
     * 
     * @type {number}
     * @memberof TextEntryQuestionDefinition
     */
    'NextChoiceId'?: number;
    /**
     * 
     * @type {string}
     * @memberof TextEntryQuestionDefinition
     */
    'QuestionDescription': string;
    /**
     * The unique identifier for the question.
     * @type {string}
     * @memberof TextEntryQuestionDefinition
     */
    'QuestionID'?: string;
    /**
     * Text for the question.
     * @type {string}
     * @memberof TextEntryQuestionDefinition
     */
    'QuestionText': string;
    /**
     * The type of question.
     * @type {QuestionType}
     * @memberof TextEntryQuestionDefinition
     */
    'QuestionType': QuestionType;
    /**
     * 
     * @type {string}
     * @memberof TextEntryQuestionDefinition
     */
    'Selector': TextEntryQuestionDefinitionSelectorEnum;
    /**
     * 
     * @type {Validation}
     * @memberof TextEntryQuestionDefinition
     */
    'Validation': Validation;
}

type TextEntryQuestionDefinitionSelectorEnum = 'SL' | 'ML' | 'ESTB' | 'FORM' | 'PW'


