/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BlockElementsInner } from './block-elements-inner';

/**
 * Exactly one Trash block per survey. Questions deleted from the UI are stored here for resuscitation
 * @export
 * @interface TrashBlock
 */
export interface TrashBlock {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof TrashBlock
     */
    'Type': TrashBlockTypeEnum;
    /**
     * All of the elements contained by the block
     * @type {Array<BlockElementsInner>}
     * @memberof TrashBlock
     */
    'BlockElements'?: Array<BlockElementsInner>;
    /**
     * The ID of the survey\'s default block.
     * @type {string}
     * @memberof TrashBlock
     */
    'ID'?: string;
    /**
     * 
     * @type {string}
     * @memberof TrashBlock
     */
    'Description': string;
}

type TrashBlockTypeEnum = 'Trash'


