/*
Qualtrics Survey API

The Qualtrics Survey endpoints give you access to the structure of the surveys you create. 

Surveys have a complex structure, and you are encouraged to become familiar with the structure using your brand's Qualtrics page to build surveys at first. Then you can query those surveys using these endpoints. 

Once you are familiar, you can use this API to create surveys on the fly, or modify existing surveys in your library. 

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { KeyValuePairArrayItem } from './key-value-pair-array-item';

/**
 * Web service flow element.
 * @export
 * @interface WebServiceFlowElement
 */
export interface WebServiceFlowElement {
    /**
     * The type of web service flow element.
     * @type {string}
     * @memberof WebServiceFlowElement
     */
    'Type'?: WebServiceFlowElementTypeEnum;
    /**
     * Unique identifier. Should be of form `FL_1`
     * @type {string}
     * @memberof WebServiceFlowElement
     */
    'FlowID'?: string;
    /**
     * The URL of the web service flow element.
     * @type {string}
     * @memberof WebServiceFlowElement
     */
    'URL'?: string;
    /**
     * The method of the web service flow element.
     * @type {string}
     * @memberof WebServiceFlowElement
     */
    'Method'?: WebServiceFlowElementMethodEnum;
    /**
     * 
     * @type {Array<KeyValuePairArrayItem>}
     * @memberof WebServiceFlowElement
     */
    'RequestParams'?: Array<KeyValuePairArrayItem>;
    /**
     * 
     * @type {Array<KeyValuePairArrayItem>}
     * @memberof WebServiceFlowElement
     */
    'EditBodyParams'?: Array<KeyValuePairArrayItem>;
    /**
     * 
     * @type {Array<KeyValuePairArrayItem>}
     * @memberof WebServiceFlowElement
     */
    'Body'?: Array<KeyValuePairArrayItem>;
    /**
     * The content type of the web service flow element.
     * @type {string}
     * @memberof WebServiceFlowElement
     */
    'ContentType'?: WebServiceFlowElementContentTypeEnum;
    /**
     * 
     * @type {Array<KeyValuePairArrayItem>}
     * @memberof WebServiceFlowElement
     */
    'Headers'?: Array<KeyValuePairArrayItem>;
    /**
     * 
     * @type {Array<KeyValuePairArrayItem>}
     * @memberof WebServiceFlowElement
     */
    'ResponseMap'?: Array<KeyValuePairArrayItem>;
    /**
     * If true, \"fire and forget.\"
     * @type {boolean}
     * @memberof WebServiceFlowElement
     */
    'FireAndForget'?: boolean;
    /**
     * If true, stringify values.
     * @type {boolean}
     * @memberof WebServiceFlowElement
     */
    'StringifyValues'?: boolean;
}

type WebServiceFlowElementTypeEnum = 'WebService'
type WebServiceFlowElementMethodEnum = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'
type WebServiceFlowElementContentTypeEnum = 'application/x-www-form-urlencoded' | 'application/json'


